---
deployment:
  tasks:
    - export USERNAME=pplkitera                     # Set the username variable
    - export DOMAIN=pplkitera.com                   # Set the domain variable
    - export HOMEPATH=/home/$USERNAME             # Set the home directory path using the username variable
    - /usr/local/bin/php $HOMEPATH/laravel/artisan down  # Put Laravel into maintenance mode before deleting any files
    - /bin/rm -rf $HOMEPATH/public_html/*               # Remove all files in the public_html directory
    - /bin/rm -rf $HOMEPATH/laravel/*                  # Remove all files in the laravel directory, after putting Laravel down
    - /usr/local/cpanel/scripts/update_local_php_ini --user=$USERNAME --domain=$DOMAIN  # Update the PHP configuration for the specified domain
    - /bin/cp -R * $HOMEPATH/laravel  # Copy all files from the current directory (assumed to be the repo) to the laravel directory
    - /bin/cp -R $HOMEPATH/laravel/public/* $HOMEPATH/public_html  # Copy all files from the laravel/public directory to public_html
    - /bin/mkdir -p $HOMEPATH/laravel/public/build  # Ensure the target directory exists
    - /bin/mv $HOMEPATH/public_html/build/manifest.json $HOMEPATH/laravel/public/build/  # Move manifest.json from public_html/build to laravel/public/build
    - /bin/sed -i 's|\.\./|\.\./laravel/|g' $HOMEPATH/public_html/index.php  # Update path in public_html/index.php
    - /usr/local/bin/php $HOMEPATH/laravel/artisan migrate:fresh --seed  # Drop all tables, re-run all migrations, and run database seeders
    - /usr/local/bin/php $HOMEPATH/laravel/artisan up                # Bring Laravel out of maintenance mode as the final step
