---
deployment:
  tasks:
    # 1. Definisikan path utama untuk kemudahan
    - export DEPLOYPATH=/home/pplkiter

    # 2. Backup file .env yang sudah ada di server (jika ada)
    - /bin/mv -f ${DEPLOYPATH}/laravel/.env ${DEPLOYPATH}/.env_backup || true

    # 3. Hapus konten lama untuk memastikan instalasi bersih
    - /bin/rm -rf ${DEPLOYPATH}/public_html/*
    - /bin/rm -rf ${DEPLOYPATH}/laravel/*

    # 4. Buat kembali direktori laravel
    - /bin/mkdir -p ${DEPLOYPATH}/laravel

    # 5. Salin folder 'public' dari repo ke 'public_html' di server
    - /bin/cp -r public/* ${DEPLOYPATH}/public_html/

    # 6. Salin semua file & folder KECUALI 'public' ke direktori 'laravel' di server
    - /bin/find . -maxdepth 1 -mindepth 1 ! -name "public" -exec /bin/cp -r {} ${DEPLOYPATH}/laravel/ \;

    # 7. Sesuaikan path di index.php agar menunjuk ke folder 'laravel'
    - /bin/sed -i 's|/../bootstrap|/../laravel/bootstrap|g' ${DEPLOYPATH}/public_html/index.php
    - /bin/sed -i 's|/../vendor|/../laravel/vendor|g' ${DEPLOYPATH}/public_html/index.php

    # 8. Pulihkan .env dari backup, atau buat dari .env.example jika ini deploy pertama kali
    - if [ -f "${DEPLOYPATH}/.env_backup" ]; then /bin/mv -f ${DEPLOYPATH}/.env_backup ${DEPLOYPATH}/laravel/.env; else /bin/cp ${DEPLOYPATH}/laravel/.env.example ${DEPLOYPATH}/laravel/.env; fi
    
    # 9. Pindahkan manifest.json dari Vite/Mix build (jika ada)
    - if [ -f "${DEPLOYPATH}/public_html/build/manifest.json" ]; then /bin/mkdir -p ${DEPLOYPATH}/laravel/public/build && /bin/cp ${DEPLOYPATH}/public_html/build/manifest.json ${DEPLOYPATH}/laravel/public/build/manifest.json; fi

    # 10. Jalankan perintah artisan untuk finalisasi & optimasi 🚀
    - /usr/local/bin/php ${DEPLOYPATH}/laravel/artisan key:generate
    - /usr/local/bin/php ${DEPLOYPATH}/laravel/artisan config:cache
    - /usr/local/bin/php ${DEPLOYPATH}/laravel/artisan route:cache
    - /usr/local/bin/php ${DEPLOYPATH}/laravel/artisan view:cache