// Generated by https://quicktype.io

export interface Question {
  id: number;
  teks_pertanyaan: string;
  answers: Answer[];
}

export interface Answer {
  id: number;
  question_id: number;
  teks_jawaban: string;
}
